### PR TITLE
performance tweaks

### PR DESCRIPTION
**Pull request by stopspazzing**
Xamarin suggestions to simplify and increase speed.

### CODE REVIEW

**Comment by SnakeTheRipper** [comment]
Why CurrentCulture instead of Ordinal ?

**Comment by Viproz** [comment]
test this please

**Comment by stopspazzing** [comment]
Good question, that was before I actually read into the differences, Ordinal is faster.

**Comment by Viproz** [comment]
please test this

**Comment by Viproz** [comment]
test this please

**Pull request merged**
