### PR TITLE
New files required

### PR DESCRIPTION
**Pull request by SkullyDev**

### CODE REVIEW

**Comment by stopspazzing** [comment]
This should fix the latest update issues. I haven't tested this yet but those extra files seem to solve the 11 errors you get when you compile against the latest rust files.

**Comment by Viproz** [comment]
Test this please

**Comment by Viproz** [comment]
Please add <Private>False</Private> to all the new dlls, like it's done for Assembly-CSharp.
Without it it copies the dll into the build folder and this is an unwanted behavior for the auto-build

**Comment by stopspazzing** [comment]
Has this been checked?

**Comment by SkullyDev** [comment]
Like Viproz said I added private tags and that is it.

**Pull request merged**
