### PR TITLE
Adding DamageTypes enum

### PR DESCRIPTION
**Pull request by SnakeTheRipper**

### CODE REVIEW

**Comment by balu92** [comment]
What's this for? Could you provide an example?

**Comment by SnakeTheRipper** [comment]
Instead of writing this sentence to null fall damage

he.DamageAmounts[12] = 0f;

We could use 

he.DamageAmounts[DamageTypes.Fall] = 0f;

And so we wouldn't need to be looking at which number is the one that refers as x type of damage. Just to make it easier.

**Comment by SnakeTheRipper** [comment]
Also, I just noticed DeathEvent uses this too, so it could be moved to a class to make it available for HurtEvent and DeathEvent and not repeat code.

**Comment by balu92** [comment]
Then we should use static indexes, like:
```
public enum DamageTypes {
    Generic = 0,
    Hunger = 1,
...
}
```

**Comment by balu92** [comment]
Tho iirc there is already an enum for this in the Assembly-CSharp.dll

**Comment by SnakeTheRipper** [comment]
Ummm I thought there was no need to explicitly set the number, they were given automatically by order.

**Comment by balu92** [comment]
Rust.DamageType is the enum what you are looking for!
https://gist.github.com/anonymous/a0804c41972c522bd3c8

**Comment by SnakeTheRipper** [comment]
Oh I see, thanks !

**Pull request closed without merging**
